### ISSUE TITLE
Exception if input file does not exist.

### ISSUE THREAD

**Issue by robmen** [2dave/github-testing#8]
A `FileNotFoundException` is thrown after printing a friendly error message. Expect a clean exit.

**Comment by 2dave** [comment]
The 'using' block is a little confusing. The only real exception handling I have dealt with is a 'try' - 'catch' block in C++. However, since 'using' seems to break down into a try - catch block, I am getting confused on if I should nest the using block inside the try - catch. I'm looking for some clues online. Any suggestions are appreciated.

**Comment by robmen** [comment]
The exception is thrown when accessing a file that does not exist. You have code that checks for file existence but continues even if it does not exist.

To test, change the path to the test file to a name that does not exist. 😈
